apiVersion: v1
kind: Service
metadata:
  name: nextjs-nodeport-service
  namespace: nextjs-app
spec:
  type: NodePort
  selector:
    app: nextjs-deployment
  ports:
    - name: http
      port: 80
      targetPort: 30001  # NGINX HTTP port inside pod
      nodePort: 30001    # External port
      protocol: TCP
    - name: https
      port: 443
      targetPort: 30002  # NGINX HTTPS port inside pod
      nodePort: 30002    # External port
      protocol: TCP
